v = input('Digite algo: ')
print('Você digitou uma variável {} (tipo primitivo)'.format(type(v)))
print('Esta variável pode ser: ')
print('- Numérica? {}'.format(v.isnumeric()))
print('- Alfabética? {}'.format(v.isalpha()))
print('- Alfanumérica? {}'.format(v.isalnum()))
print('- Somente espaços? {}'.format(v.isspace()))
print('- Somente maiúsculas? {}'.format(v.isupper()))
print('- Somente minúsculas? {}'.format(v.islower()))
print('- Capitalizada? {}'.format(v.istitle()))